// <auto-generated />
using BrikonYapi.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BrikonYapi.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260421200000_AddMissingTables")]
    partial class AddMissingTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
